#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGenerator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThePokeBase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PokemonGenerator.Properties.Settings.Default.ThePokeBaseConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vwPokemonMove> vwPokemonMoves
		{
			get
			{
				return this.GetTable<vwPokemonMove>();
			}
		}
		
		public System.Data.Linq.Table<vwGenIIMove> vwGenIIMoves
		{
			get
			{
				return this.GetTable<vwGenIIMove>();
			}
		}
		
		public System.Data.Linq.Table<vwGenIIItem> vwGenIIItems
		{
			get
			{
				return this.GetTable<vwGenIIItem>();
			}
		}
		
		public System.Data.Linq.Table<vwEvolution> vwEvolutions
		{
			get
			{
				return this.GetTable<vwEvolution>();
			}
		}
		
		public System.Data.Linq.Table<vwBaseStat> vwBaseStats
		{
			get
			{
				return this.GetTable<vwBaseStat>();
			}
		}
		
		public System.Data.Linq.Table<vwTM> vwTMs
		{
			get
			{
				return this.GetTable<vwTM>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPokemonByLevelStrict")]
		public ISingleResult<GetPokemonByLevelStrictResult> GetPokemonByLevelStrict([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lvl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lvl);
			return ((ISingleResult<GetPokemonByLevelStrictResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetWeaknesses")]
		public ISingleResult<uspGetWeaknessesResult> uspGetWeaknesses([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string typesString)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), typesString);
			return ((ISingleResult<uspGetWeaknessesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetPokemonMoveSet")]
		public ISingleResult<uspGetPokemonMoveSetResult> uspGetPokemonMoveSet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lvl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, lvl);
			return ((ISingleResult<uspGetPokemonMoveSetResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwPokemonMoves")]
	public partial class vwPokemonMove
	{
		
		private int _pokemon_id;
		
		private int _move_id;
		
		private string _method;
		
		private int _level;
		
		public vwPokemonMove()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pokemon_id", DbType="Int NOT NULL")]
		public int pokemon_id
		{
			get
			{
				return this._pokemon_id;
			}
			set
			{
				if ((this._pokemon_id != value))
				{
					this._pokemon_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_move_id", DbType="Int NOT NULL")]
		public int move_id
		{
			get
			{
				return this._move_id;
			}
			set
			{
				if ((this._move_id != value))
				{
					this._move_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method", DbType="NVarChar(79)")]
		public string method
		{
			get
			{
				return this._method;
			}
			set
			{
				if ((this._method != value))
				{
					this._method = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int NOT NULL")]
		public int level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwGenIIMoves")]
	public partial class vwGenIIMove
	{
		
		private int _moveId;
		
		private string _moveName;
		
		private string _identifier;
		
		private System.Nullable<short> _power;
		
		private System.Nullable<short> _pp;
		
		private string _damageType;
		
		private string _effect;
		
		public vwGenIIMove()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moveId", DbType="Int NOT NULL")]
		public int moveId
		{
			get
			{
				return this._moveId;
			}
			set
			{
				if ((this._moveId != value))
				{
					this._moveId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moveName", DbType="NVarChar(79) NOT NULL", CanBeNull=false)]
		public string moveName
		{
			get
			{
				return this._moveName;
			}
			set
			{
				if ((this._moveName != value))
				{
					this._moveName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(79)")]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this._identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_power", DbType="SmallInt")]
		public System.Nullable<short> power
		{
			get
			{
				return this._power;
			}
			set
			{
				if ((this._power != value))
				{
					this._power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pp", DbType="SmallInt")]
		public System.Nullable<short> pp
		{
			get
			{
				return this._pp;
			}
			set
			{
				if ((this._pp != value))
				{
					this._pp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_damageType", DbType="NVarChar(79)")]
		public string damageType
		{
			get
			{
				return this._damageType;
			}
			set
			{
				if ((this._damageType != value))
				{
					this._damageType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect", DbType="NVarChar(MAX)")]
		public string effect
		{
			get
			{
				return this._effect;
			}
			set
			{
				if ((this._effect != value))
				{
					this._effect = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwGenIIItems")]
	public partial class vwGenIIItem
	{
		
		private int _game_index;
		
		private string _identifier;
		
		public vwGenIIItem()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_index", DbType="Int NOT NULL")]
		public int game_index
		{
			get
			{
				return this._game_index;
			}
			set
			{
				if ((this._game_index != value))
				{
					this._game_index = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(79) NOT NULL", CanBeNull=false)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this._identifier = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwEvolutions")]
	public partial class vwEvolution
	{
		
		private int _id;
		
		private string _identifier;
		
		private System.Nullable<int> _evolvedFromPrevID;
		
		private System.Nullable<int> _evolution_trigger_id;
		
		private System.Nullable<int> _minimum_level;
		
		public vwEvolution()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(79) NOT NULL", CanBeNull=false)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this._identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evolvedFromPrevID", DbType="Int")]
		public System.Nullable<int> evolvedFromPrevID
		{
			get
			{
				return this._evolvedFromPrevID;
			}
			set
			{
				if ((this._evolvedFromPrevID != value))
				{
					this._evolvedFromPrevID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evolution_trigger_id", DbType="Int")]
		public System.Nullable<int> evolution_trigger_id
		{
			get
			{
				return this._evolution_trigger_id;
			}
			set
			{
				if ((this._evolution_trigger_id != value))
				{
					this._evolution_trigger_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimum_level", DbType="Int")]
		public System.Nullable<int> minimum_level
		{
			get
			{
				return this._minimum_level;
			}
			set
			{
				if ((this._minimum_level != value))
				{
					this._minimum_level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwBaseStats")]
	public partial class vwBaseStat
	{
		
		private int _id;
		
		private string _identifier;
		
		private string _Types;
		
		private System.Nullable<int> _hp;
		
		private System.Nullable<int> _attack;
		
		private System.Nullable<int> _defense;
		
		private System.Nullable<int> _spAttack;
		
		private System.Nullable<int> _spDefense;
		
		private System.Nullable<int> _speed;
		
		private string _growthRate;
		
		public vwBaseStat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(79) NOT NULL", CanBeNull=false)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this._identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Types", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Types
		{
			get
			{
				return this._Types;
			}
			set
			{
				if ((this._Types != value))
				{
					this._Types = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hp", DbType="Int")]
		public System.Nullable<int> hp
		{
			get
			{
				return this._hp;
			}
			set
			{
				if ((this._hp != value))
				{
					this._hp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attack", DbType="Int")]
		public System.Nullable<int> attack
		{
			get
			{
				return this._attack;
			}
			set
			{
				if ((this._attack != value))
				{
					this._attack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defense", DbType="Int")]
		public System.Nullable<int> defense
		{
			get
			{
				return this._defense;
			}
			set
			{
				if ((this._defense != value))
				{
					this._defense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spAttack", DbType="Int")]
		public System.Nullable<int> spAttack
		{
			get
			{
				return this._spAttack;
			}
			set
			{
				if ((this._spAttack != value))
				{
					this._spAttack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spDefense", DbType="Int")]
		public System.Nullable<int> spDefense
		{
			get
			{
				return this._spDefense;
			}
			set
			{
				if ((this._spDefense != value))
				{
					this._spDefense = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="Int")]
		public System.Nullable<int> speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_growthRate", DbType="NVarChar(79)")]
		public string growthRate
		{
			get
			{
				return this._growthRate;
			}
			set
			{
				if ((this._growthRate != value))
				{
					this._growthRate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwTMs")]
	public partial class vwTM
	{
		
		private int _move_id;
		
		public vwTM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_move_id", DbType="Int NOT NULL")]
		public int move_id
		{
			get
			{
				return this._move_id;
			}
			set
			{
				if ((this._move_id != value))
				{
					this._move_id = value;
				}
			}
		}
	}
	
	public partial class GetPokemonByLevelStrictResult
	{
		
		private int _id;
		
		private string _identifier;
		
		private System.Nullable<int> _evolvedFromPrevID;
		
		private System.Nullable<int> _evolution_trigger_id;
		
		private System.Nullable<int> _minimum_level;
		
		public GetPokemonByLevelStrictResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(79) NOT NULL", CanBeNull=false)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this._identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evolvedFromPrevID", DbType="Int")]
		public System.Nullable<int> evolvedFromPrevID
		{
			get
			{
				return this._evolvedFromPrevID;
			}
			set
			{
				if ((this._evolvedFromPrevID != value))
				{
					this._evolvedFromPrevID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evolution_trigger_id", DbType="Int")]
		public System.Nullable<int> evolution_trigger_id
		{
			get
			{
				return this._evolution_trigger_id;
			}
			set
			{
				if ((this._evolution_trigger_id != value))
				{
					this._evolution_trigger_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimum_level", DbType="Int")]
		public System.Nullable<int> minimum_level
		{
			get
			{
				return this._minimum_level;
			}
			set
			{
				if ((this._minimum_level != value))
				{
					this._minimum_level = value;
				}
			}
		}
	}
	
	public partial class uspGetWeaknessesResult
	{
		
		private string _identifier;
		
		public uspGetWeaknessesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(79)")]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this._identifier = value;
				}
			}
		}
	}
	
	public partial class uspGetPokemonMoveSetResult
	{
		
		private int _level;
		
		private int _moveId;
		
		private string _moveName;
		
		private string _Type;
		
		private System.Nullable<short> _power;
		
		private System.Nullable<short> _pp;
		
		private string _damageType;
		
		private string _effect;
		
		public uspGetPokemonMoveSetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int NOT NULL")]
		public int level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moveId", DbType="Int NOT NULL")]
		public int moveId
		{
			get
			{
				return this._moveId;
			}
			set
			{
				if ((this._moveId != value))
				{
					this._moveId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moveName", DbType="NVarChar(79) NOT NULL", CanBeNull=false)]
		public string moveName
		{
			get
			{
				return this._moveName;
			}
			set
			{
				if ((this._moveName != value))
				{
					this._moveName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(79)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_power", DbType="SmallInt")]
		public System.Nullable<short> power
		{
			get
			{
				return this._power;
			}
			set
			{
				if ((this._power != value))
				{
					this._power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pp", DbType="SmallInt")]
		public System.Nullable<short> pp
		{
			get
			{
				return this._pp;
			}
			set
			{
				if ((this._pp != value))
				{
					this._pp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_damageType", DbType="NVarChar(79)")]
		public string damageType
		{
			get
			{
				return this._damageType;
			}
			set
			{
				if ((this._damageType != value))
				{
					this._damageType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect", DbType="NVarChar(MAX)")]
		public string effect
		{
			get
			{
				return this._effect;
			}
			set
			{
				if ((this._effect != value))
				{
					this._effect = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
